const data = [
  {
    name: 'inlet_moisture',
    channum: 300,
    sztag: 'DAI_INLET_MOISTURE',
    column: 'pv',
    value: 0.0,
    table: 'io_table',
    minRange: 0,
    maxRange: 50,
  },
  {
    name: 'inlet_temperature',
    channum: 308,
    sztag: 'DAI_INLET_TEMP',
    column: 'pv',
    value: 0.0,
    table: 'io_table',
    minRange: 0,
    maxRange: 450,
  },
  {
    name: 'outlet_moisture',
    channum: 301,
    sztag: 'DAI_OUTLET_MOISTURE',
    column: 'pv',
    value: 0.0,
    table: 'io_table',
    minRange: 0,
    maxRange: 50,
  },
  {
    name: 'outlet_temperature',
    channum: 307,
    sztag: 'DAI_OUTLET_TEMP',
    column: 'pv',
    value: 0.0,
    table: 'io_table',
    minRange: 0,
    maxRange: 450,
  },
  {
    name: 'drying_temperature',
    channum: 52,
    sztag: 'CDP_OUTLET_TEMP1',
    column: 'pv',
    value: 0.0,
    table: 'io_table',
    minRange: 0,
    maxRange: 700,
  },
  {
    name: 'discharge_rate',
    channum: 49,
    sztag: 'DAI_DISPLAY_RATE',
    column: 'pv',
    value: 0.0,
    table: 'io_table',
    minRange: 0,
    maxRange: 20000,
  },
];

module.exports = data;
